dist: Xenial
language: python
sudo: required

python:
  - "3.7"

# Installing Chrome for e2e tests
addons:
  chrome: stable

before_install:
  - wget -N http://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - mv -f ~/chromedriver /usr/local/share/
  - chmod +x /usr/local/share/chromedriver
  - ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

install:
    - "pip install -r requirements.txt"

script:
   - "whereis google-chrome-stable"
   - "whereis chromedriver"
   - "whereis forgot_login_all_fields_empty_test.py"
   - "pytest tests/"

after_script:
  - "sh -e /etc/init.d/xvfb stop"

# Source: https://flatmap.it/2017/11/16/starting-selenium-server-inside-travis/