sudo: required

dist: trusty

language: python

python:
  - "3.6"

# setting up environment variables
env:
  global:
    - CXX=g++-4.8
    - DISPLAY=:99.0
    - CHROME_BIN=/usr/bin/google-chrome

# installing Chrome for e2e tests
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# the following step should start the virtual X frame buffer: Xvfb process
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 #wait a while before xvfb to start

install:
    - "pip install pytest"
    - "pip install selenium"
    - "pip install allure-pytest"
    - "pip install allure-python-commons"
    - "pip install requests"

script:
   - "whereis google-chrome-stable"
   - "whereis chromedriver"
   - "whereis forgot_login_all_fields_empty_test.py"
   - "pytest tests/e2e_tests/forgot_login/forgot_login_all_fields_empty_test.py"

after_script:
  - "sh -e /etc/init.d/xvfb stop"
