dist: Xenial
language: python
sudo: required

python:
  - "3.7"

# Installing Chrome for e2e tests
addons:
  chrome: stable

before_install:
  - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - mv -f ~/chromedriver /usr/local/bin/chromedriver
  - chmod +x /usr/local/bin/chromedriver

install:
    - "pip install -r requirements.txt"

script:
   - "whereis google-chrome-stable"
   - "whereis chromedriver"
   - "pytest tests/"

# Source:
# https://www.youtube.com/watch?v=kxEKygtd2eM
# https://www.amihaiemil.com/2017/07/14/selenium-headless-chrome-travis.html