dist: trusty
language: python
sudo: required

python:
  - "3.6"

# Installing Chrome for e2e tests
addons:
  chrome: stable

before_install:
  #- "wget https://chromedriver.storage.googleapis.com/77.0.3865.10/chromedriver_linux64.zip"
  - "wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip"
  - "sudo unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/"

install:
    - "pip install -r requirements.txt"

script:
   - "whereis google-chrome-stable"
   - "whereis chromedriver"
   - "whereis forgot_login_all_fields_empty_test.py"
   - "pytest tests/content_tests"

after_script:
  - "sh -e /etc/init.d/xvfb stop"

# Source: https://flatmap.it/2017/11/16/starting-selenium-server-inside-travis/