dist: trusty
language: python
sudo: required

python:
  - "3.6"

# Installing Chrome for e2e tests
addons:
  chrome: stable

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/local/bin/
  - rm chromedriver_linux64.zip

install:
    - "pip install -r requirements.txt"

script:
   - "whereis google-chrome-stable"
   - "whereis chromedriver"
   - "pytest -v tests/"

# Source:
# https://www.youtube.com/watch?v=kxEKygtd2eM
